spring.application.name=controle-cabos
# Nome da aplicação
spring.application.name=controle-cabos

# Configurações do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:estoquedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o painel do banco no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cria as tabelas automaticamente baseado no código Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Java está executando por baixo dos panos
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console