# 1. Credenciais da Nuvem (Neon PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-steep-frost-acbgokoi-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_l5AdFyKs0bzJ

# 2. Configurações de Driver e Dialeto do Postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Inteligência do Hibernate (Cria e atualiza as tabelas na nuvem automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true